spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scm
    username: root
    password: RECOMMENDED
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect